#pragma once

#include "common.h"

void LoadSprites();
void UnloadSprites();

enum SpriteID {
  SPRITE_BODY_LL = 0,
  SPRITE_BODY_UL,
  SPRITE_TAIL_L,
  SPRITE_BODY_DL,
  SPRITE_HEAD_RR,
  SPRITE_HEAD_RD,
  SPRITE_UNUSED_1,
  SPRITE_HEAD_RU,
  SPRITE_BODY_LU,
  SPRITE_BODY_UU,
  SPRITE_BODY_RU,
  SPRITE_TAIL_U,
  SPRITE_HEAD_DR,
  SPRITE_HEAD_DD,
  SPRITE_HEAD_DL,
  SPRITE_UNUSED_2,
  SPRITE_TAIL_R,
  SPRITE_BODY_UR,
  SPRITE_BODY_RR,
  SPRITE_BODY_DR,
  SPRITE_UNUSED_3,
  SPRITE_HEAD_LD,
  SPRITE_HEAD_LL,
  SPRITE_HEAD_LU,
  SPRITE_BODY_LD,
  SPRITE_TAIL_D,
  SPRITE_BODY_RD,
  SPRITE_BODY_DD,
  SPRITE_HEAD_UR,
  SPRITE_APPLE,
  SPRITE_HEAD_UL,
  SPRITE_HEAD_UU,
};

void DrawSprite(Pos, SpriteID);
